/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

//build with gradle run --args='server 5050' format to pass mode and port

// import org.gradle.api.tasks.testing.logging.TestExceptionFormat
// import org.gradle.api.tasks.testing.logging.TestLogEvent

import com.adarshr.gradle.testlogger.theme.ThemeType

version = "0.0.1"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id ("com.adarshr.test-logger") version "2.0.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

application {
    // Define the main class for the application.
    mainClass.set("com.lukemcconnell.shoot.messenger.App")
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "com.lukemcconnell.shoot.messenger.App"
    }
}

tasks.withType<JavaExec>() {
    standardInput = System.`in`
}